packageExtensions:
  '@loopback/eslint-config@*':
    dependencies:
      'eslint-plugin-eslint-plugin': ^2.3.0
  '@loopback/openapi-v3@*':
    dependencies:
      '@loopback/repository': ^2.11.2
  '@typescript-eslint/eslint-plugin@*':
    dependencies:
      '@typescript-eslint/parser': ^4.4.0
  '@types/sinon@*':
    dependencies:
      '@sinonjs/fake-timers': ^6.0.1
  '@loopback/repository@*':
    dependencies:
      'json-schema': ^0.2.3
      '@types/json-schema': ^7.0.6
  'strong-error-handler@*':
    dependencies:
      'express': ^4.17.1
  '@types/express@*':
    dependencies:
      'serve-static': ^1.14.1
      'body-parser': ^1.19.0
      'qs': ^6.9.4
  '@types/express-serve-static-core@*':
    dependencies:
      'range-parser': ^1.2.1
      'qs': ^6.9.4
  '@types/serve-static@*':
    dependencies:
      'mime': ^1.6.0
  '@loopback/repository-json-schema@*':
    dependencies:
      'json-schema': ^0.2.3
  '@loopback/rest@*':
    dependencies:
      'serve-static': ^1.14.1
  '@types/cors@*':
    dependencies:
      'express': ^4.17.1
  '@types/supertest@*':
    dependencies:
      'superagent': ^6.1.0
      'cookiejar': ^2.1.2
  '@types/superagent@*':
    dependencies:
      'cookiejar': ^2.1.2
  'swagger-ui-dist@*':
    dependencies:
      'esprima': ^4.0.0
  'strong-globalize@*':
    dependencies:
      'cldrjs': ^0.5.4
  'debug@*':
    dependencies:
      'supports-color': ^7.1.0
  '@node-rs/helper@*':
    dependencies:
      '@swc/core-linux-musl': ^1.2.36
      '@swc/core-linux': ^1.2.36
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs
